### PR TITLE
.NET5 support #8

### LINKED ISSUE #8: .Net 5 support
.Net 5 is the next major .net version which replace .net 4.x and is based on .net core code base. 

Microsoft [released the last RC](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/) and it would be to also have .net 5 support when .net 5 is released as stable version.

Here is a [breaking change to 3.1 in terms of used SDK](https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#winforms-and-wpf-apps-use-microsoftnetsdk)

### PR DESCRIPTION
**Pull request by MagicAndre1981**
fixed #8 : .NET5 support

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
@JohannBlais will this be ever merged and updated for .net 6?

**Comment by valimaties** [comment]
I've made a PR too and I don't see it merged... Is this project maintained anymore?

**Comment by MagicAndre1981** [comment]
> I've made a PR too and I don't see it merged... Is this project maintained anymore?

I have no idea. I haven't heard anything from @JohannBlais for a while.

**Comment by JohannBlais** [comment]
Hi, I apologise for the very late feedback. As .NET 5.0 is not supported anymore and the latest package now supports .NET 6.0, this PR will not be merged.
Thank you very much for your submission though !

**Pull request closed without merging**
